# pubspec.yaml
name: image_downloader
description: Flutter plugin that downloads images on the Internet and saves them on device.
version: 0.33.0+1
homepage: https://github.com/ko2ic/image_downloader

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ko2ic.imagedownloader
        pluginClass: ImageDownloaderPlugin
      ios:
        pluginClass: SwiftImageDownloaderPlugin
